"""XPath-only locators for the ParaBank UI."""

XPATH_HOME_USERNAME = "xpath=//input[@name='username']"
XPATH_HOME_PASSWORD = "xpath=//input[@name='password']"
XPATH_HOME_LOGIN_BUTTON = "xpath=//input[@value='Log In']"
XPATH_HOME_REGISTER_LINK = "xpath=//a[@href='register.htm' or contains(@href,'register.htm')]"
XPATH_HOME_FORGOT_LINK = "xpath=//a[contains(@href,'lookup.htm')]"
XPATH_PAGE_HEADING = "xpath=//h1[contains(@class,'title')]"
XPATH_ERROR_MESSAGE = "xpath=//p[contains(@class,'error')]"
XPATH_ERROR_LIST = "xpath=//span[contains(@class,'error') or contains(@class,'error')]"
XPATH_SUCCESS_MESSAGE = "xpath=//div[@id='rightPanel']//p"
XPATH_CONTENT_HEADING = "xpath=//div[@id='rightPanel']//h1"
XPATH_RIGHT_PANEL = "xpath=//div[@id='rightPanel']"
XPATH_REGISTER_FIRST_NAME = "xpath=//input[@id='customer.firstName']"
XPATH_REGISTER_LAST_NAME = "xpath=//input[@id='customer.lastName']"
XPATH_REGISTER_ADDRESS = "xpath=//input[@id='customer.address.street']"
XPATH_REGISTER_CITY = "xpath=//input[@id='customer.address.city']"
XPATH_REGISTER_STATE = "xpath=//input[@id='customer.address.state']"
XPATH_REGISTER_ZIP = "xpath=//input[@id='customer.address.zipCode']"
XPATH_REGISTER_PHONE = "xpath=//input[@id='customer.phoneNumber']"
XPATH_REGISTER_SSN = "xpath=//input[@id='customer.ssn']"
XPATH_REGISTER_USERNAME = "xpath=//input[@id='customer.username']"
XPATH_REGISTER_PASSWORD = "xpath=//input[@id='customer.password']"
XPATH_REGISTER_CONFIRM_PASSWORD = "xpath=//input[@id='repeatedPassword']"
XPATH_REGISTER_BUTTON = "xpath=//form[@id='customerForm']//input[@value='Register']"
XPATH_REGISTER_FORM = "xpath=//form[@id='customerForm']"
XPATH_LOOKUP_FIRST_NAME = "xpath=//input[@id='firstName']"
XPATH_LOOKUP_LAST_NAME = "xpath=//input[@id='lastName']"
XPATH_LOOKUP_ADDRESS = "xpath=//input[@id='address.street']"
XPATH_LOOKUP_CITY = "xpath=//input[@id='address.city']"
XPATH_LOOKUP_STATE = "xpath=//input[@id='address.state']"
XPATH_LOOKUP_ZIP = "xpath=//input[@id='address.zipCode']"
XPATH_LOOKUP_SSN = "xpath=//input[@id='ssn']"
XPATH_LOOKUP_BUTTON = "xpath=//input[@value='Find My Login Info']"
XPATH_LEFT_MENU_LINKS = "xpath=//div[@id='leftPanel']//a"
XPATH_NAV_OPEN_ACCOUNT = "xpath=//div[@id='leftPanel']//a[normalize-space()='Open New Account']"
XPATH_NAV_OVERVIEW = "xpath=//div[@id='leftPanel']//a[normalize-space()='Accounts Overview']"
XPATH_NAV_TRANSFER = "xpath=//div[@id='leftPanel']//a[normalize-space()='Transfer Funds']"
XPATH_NAV_BILL_PAY = "xpath=//div[@id='leftPanel']//a[normalize-space()='Bill Pay']"
XPATH_NAV_FIND_TRANSACTIONS = "xpath=//div[@id='leftPanel']//a[normalize-space()='Find Transactions']"
XPATH_NAV_UPDATE_PROFILE = "xpath=//div[@id='leftPanel']//a[normalize-space()='Update Contact Info']"
XPATH_NAV_REQUEST_LOAN = "xpath=//div[@id='leftPanel']//a[normalize-space()='Request Loan']"
XPATH_NAV_LOGOUT = "xpath=//div[@id='leftPanel']//a[normalize-space()='Log Out']"
XPATH_OPEN_ACCOUNT_TYPE = "xpath=//select[@id='type']"
XPATH_OPEN_ACCOUNT_FROM = "xpath=//select[@id='fromAccountId']"
XPATH_OPEN_ACCOUNT_BUTTON = "xpath=//input[@value='Open New Account']"
XPATH_NEW_ACCOUNT_ID = "xpath=//a[@id='newAccountId']"
XPATH_ACCOUNT_TABLE = "xpath=//table[@id='accountTable']"
XPATH_ACCOUNT_ROWS = "xpath=//table[@id='accountTable']//tr"
XPATH_ACCOUNT_BALANCE = "xpath=//table[@id='accountTable']//a[contains(@href,'activity.htm')]"
XPATH_TRANSFER_AMOUNT = "xpath=//input[@id='amount']"
XPATH_TRANSFER_FROM = "xpath=//select[@id='fromAccountId']"
XPATH_TRANSFER_TO = "xpath=//select[@id='toAccountId']"
XPATH_TRANSFER_ACCOUNT_OPTIONS = "xpath=//select[@id='fromAccountId']/option"
XPATH_TRANSFER_BUTTON = "xpath=//input[@value='Transfer']"
XPATH_TRANSFER_RESULT = "xpath=//div[@id='showResult']"
XPATH_BILL_NAME = "xpath=//input[@name='payee.name']"
XPATH_BILL_ADDRESS = "xpath=//input[@name='payee.address.street']"
XPATH_BILL_CITY = "xpath=//input[@name='payee.address.city']"
XPATH_BILL_STATE = "xpath=//input[@name='payee.address.state']"
XPATH_BILL_ZIP = "xpath=//input[@name='payee.address.zipCode']"
XPATH_BILL_PHONE = "xpath=//input[@name='payee.phoneNumber']"
XPATH_BILL_ACCOUNT = "xpath=//input[@name='payee.accountNumber']"
XPATH_BILL_CONFIRM_ACCOUNT = "xpath=//input[@name='verifyAccount']"
XPATH_BILL_AMOUNT = "xpath=//input[@name='amount']"
XPATH_BILL_FROM_ACCOUNT = "xpath=//select[@name='fromAccountId']"
XPATH_BILL_BUTTON = "xpath=//input[@value='Send Payment']"
XPATH_BILL_RESULT = "xpath=//div[@id='billpayResult']"
XPATH_PROFILE_FIRST_NAME = "xpath=//input[@id='customer.firstName']"
XPATH_PROFILE_LAST_NAME = "xpath=//input[@id='customer.lastName']"
XPATH_PROFILE_ADDRESS = "xpath=//input[@id='customer.address.street']"
XPATH_PROFILE_CITY = "xpath=//input[@id='customer.address.city']"
XPATH_PROFILE_STATE = "xpath=//input[@id='customer.address.state']"
XPATH_PROFILE_ZIP = "xpath=//input[@id='customer.address.zipCode']"
XPATH_PROFILE_PHONE = "xpath=//input[@id='customer.phoneNumber']"
XPATH_PROFILE_UPDATE_BUTTON = "xpath=//input[@value='Update Profile']"
XPATH_LOAN_AMOUNT = "xpath=//input[@id='amount']"
XPATH_LOAN_DOWN_PAYMENT = "xpath=//input[@id='downPayment']"
XPATH_LOAN_FROM_ACCOUNT = "xpath=//select[@id='fromAccountId']"
XPATH_LOAN_BUTTON = "xpath=//input[@value='Apply Now']"
XPATH_LOAN_RESULT = "xpath=//div[@id='loanRequestResult']"
XPATH_FIND_ACCOUNT = "xpath=//select[@id='accountId']"
XPATH_FIND_TRANSACTION_ID = "xpath=//input[@id='transactionId']"
XPATH_FIND_DATE = "xpath=//input[@id='transactionDate']"
XPATH_FIND_FROM_DATE = "xpath=//input[@id='fromDate']"
XPATH_FIND_TO_DATE = "xpath=//input[@id='toDate']"
XPATH_FIND_AMOUNT = "xpath=//input[@id='amount']"
XPATH_FIND_BY_ID_BUTTON = "xpath=//button[@id='findById']"
XPATH_FIND_BY_DATE_BUTTON = "xpath=//button[@id='findByDate']"
XPATH_FIND_BY_RANGE_BUTTON = "xpath=//button[@id='findByDateRange']"
XPATH_FIND_BY_AMOUNT_BUTTON = "xpath=//button[@id='findByAmount']"
XPATH_TRANSACTION_TABLE = "xpath=//table[@id='transactionTable']"
XPATH_GLOBAL_ABOUT_LINK = "xpath=//div[@id='headerPanel']//a[normalize-space()='about']"
XPATH_GLOBAL_SERVICES_LINK = "xpath=//div[@id='headerPanel']//a[normalize-space()='Services']"
XPATH_GLOBAL_CONTACT_LINK = "xpath=//div[@id='headerPanel']//a[normalize-space()='contact']"
XPATH_ABOUT_HEADING = "xpath=//div[@id='rightPanel']//h1"
XPATH_SERVICES_HEADING = "xpath=//div[@id='rightPanel']//h1"
XPATH_CONTACT_HEADING = "xpath=//div[@id='rightPanel']//h1"
